[profile.release]
panic = 'unwind'

[workspace]
exclude = [
	"vendors/ring",
	"vendors/webpki",
	"substrate",
]

members = [
    'node',
	'rpc',
	'primitives',
    'pallets/*',
    'runtime',
]

resolver = "2"
