[package]
name = "deer-rpc"
version = "0.1.0"
edition = "2018"
license = "Apache 2.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "15.1.0"
node-primitives = { package = "deer-primitives", version = "0.1.0", path = "../primitives" }
pallet-transaction-payment-rpc = { version = "3.0.0", path = "../../substrate/frame/transaction-payment/rpc/" }
sc-client-api = { version = "3.0.0", path = "../../substrate/client/api" }
sc-consensus-babe = { version = "0.9.0", path = "../../substrate/client/consensus/babe" }
sc-consensus-babe-rpc = { version = "0.9.0", path = "../../substrate/client/consensus/babe/rpc" }
sc-consensus-epochs = { version = "0.9.0", path = "../../substrate/client/consensus/epochs" }
sc-chain-spec = { version = "3.0.0", path = "../../substrate/client/chain-spec" }
sc-finality-grandpa = { version = "0.9.0", path = "../../substrate/client/finality-grandpa" }
sc-finality-grandpa-rpc = { version = "0.9.0", path = "../../substrate/client/finality-grandpa/rpc" }
sc-keystore = { version = "3.0.0", path = "../../substrate/client/keystore" }
sc-rpc-api = { version = "0.9.0", path = "../../substrate/client/rpc-api" }
sc-rpc = { version = "3.0.0", path = "../../substrate/client/rpc" }
sc-sync-state-rpc = { version = "0.9.0", path = "../../substrate/client/sync-state-rpc" }
sp-api = { version = "3.0.0", path = "../../substrate/primitives/api" }
sp-block-builder = { version = "3.0.0", path = "../../substrate/primitives/block-builder" }
sp-blockchain = { version = "3.0.0", path = "../../substrate/primitives/blockchain" }
sp-keystore = { version = "0.9.0", path = "../../substrate/primitives/keystore" }
sp-consensus = { version = "0.9.0", path = "../../substrate/primitives/consensus/common" }
sp-consensus-babe = { version = "0.9.0", path = "../../substrate/primitives/consensus/babe" }
sp-runtime = { version = "3.0.0", path = "../../substrate/primitives/runtime" }
sp-transaction-pool = { version = "3.0.0", path = "../../substrate/primitives/transaction-pool" }
substrate-frame-rpc-system = { version = "3.0.0", path = "../../substrate/utils/frame/rpc/system" }
