[package]
name = 'nft360'
version = '0.1.0'
build = 'build.rs'
edition = '2018'

[[bin]]
name = "nft360-node"
path = "bin/main.rs"
required-features = ["cli"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = { version = "1.0.102", features = ["derive"] }
futures = { version = "0.3.9", features = ["compat"] }
hex-literal = "0.3.1"
log = "0.4.8"
rand = "0.7.2"
structopt = { version = "0.3.8", optional = true }
parking_lot = "0.11.1"

# primitives
sp-authority-discovery = { version = "3.0.0",  path = "../../substrate/primitives/authority-discovery" }
sp-consensus-babe = { version = "0.9.0", path = "../../substrate/primitives/consensus/babe" }
grandpa-primitives = { version = "3.0.0", package = "sp-finality-grandpa", path = "../../substrate/primitives/finality-grandpa" }
sp-core = { version = "3.0.0", path = "../../substrate/primitives/core" }
sp-runtime = { version = "3.0.0", path = "../../substrate/primitives/runtime" }
sp-timestamp = { version = "3.0.0", path = "../../substrate/primitives/timestamp" }
sp-authorship = { version = "3.0.0", path = "../../substrate/primitives/authorship" }
sp-inherents = { version = "3.0.0", path = "../../substrate/primitives/inherents" }
sp-keyring = { version = "3.0.0", path = "../../substrate/primitives/keyring" }
sp-keystore = { version = "0.9.0", path = "../../substrate/primitives/keystore" }
sp-io = { version = "3.0.0", path = "../../substrate/primitives/io" }
sp-consensus = { version = "0.9.0", path = "../../substrate/primitives/consensus/common" }
sp-transaction-pool = { version = "3.0.0", path = "../../substrate/primitives/transaction-pool" }

# client dependencies
sc-client-api = { version = "3.0.0", path = "../../substrate/client/api" }
sc-chain-spec = { version = "3.0.0", path = "../../substrate/client/chain-spec" }
sc-consensus = { version = "0.9.0", path = "../../substrate/client/consensus/common" }
sc-executor = { version = "0.9.0", path = "../../substrate/client/executor" }
sc-transaction-pool = { version = "3.0.0", path = "../../substrate/client/transaction-pool" }
sc-network = { version = "0.9.0", path = "../../substrate/client/network" }
sc-consensus-slots = { version = "0.9.0", path = "../../substrate/client/consensus/slots" }
sc-consensus-babe = { version = "0.9.0", path = "../../substrate/client/consensus/babe" }
sc-consensus-uncles = { version = "0.9.0", path = "../../substrate/client/consensus/uncles" }
grandpa = { version = "0.9.0", package = "sc-finality-grandpa", path = "../../substrate/client/finality-grandpa" }
sc-client-db = { version = "0.9.0", default-features = false, path = "../../substrate/client/db" }
sc-offchain = { version = "3.0.0", path = "../../substrate/client/offchain" }
sc-rpc = { version = "3.0.0", path = "../../substrate/client/rpc" }
sc-basic-authorship = { version = "0.9.0", path = "../../substrate/client/basic-authorship" }
sc-service = { version = "0.9.0", default-features = false, path = "../../substrate/client/service" }
sc-tracing = { version = "3.0.0", path = "../../substrate/client/tracing" }
sc-telemetry = { version = "3.0.0", path = "../../substrate/client/telemetry" }
sc-authority-discovery = { version = "0.9.0",  path = "../../substrate/client/authority-discovery" }
sc-finality-grandpa-warp-sync = { version = "0.9.0", path = "../../substrate/client/finality-grandpa-warp-sync", optional = true }

# frame dependencies
frame-system = { version = "3.0.0", path = "../../substrate/frame/system" }
frame-benchmarking = { version = '3.1.0', path = '../../substrate/frame/benchmarking', default-features = false }
frame-support = { version = "3.0.0", default-features = false, path = "../../substrate/frame/support" }
pallet-indices = { version = "3.0.0", path = "../../substrate/frame/indices" }
pallet-timestamp = { version = "3.0.0", default-features = false, path = "../../substrate/frame/timestamp" }
pallet-contracts = { version = "3.0.0", path = "../../substrate/frame/contracts" }
pallet-balances = { version = "3.0.0", path = "../../substrate/frame/balances" }
pallet-transaction-payment = { version = "3.0.0", path = "../../substrate/frame/transaction-payment" }
pallet-im-online = { version = "3.0.0", default-features = false, path = "../../substrate/frame/im-online" }
pallet-authority-discovery = { version = "3.0.0", path = "../../substrate/frame/authority-discovery" }
pallet-staking = { version = "3.0.0", path = "../../substrate/frame/staking" }
pallet-grandpa = { version = "3.1.0", path = "../../substrate/frame/grandpa" }

# node-specific dependencies
node-runtime = { package = "nft360-runtime", version = "0.1.0", path = "../runtime" }
node-rpc = { package = "nft360-rpc", version = "0.1.0", path = "../rpc" }
node-primitives = { package = "nft360-primitives", version = "0.1.0", path = "../primitives" }
node-executor = { package="nft360-executor", version = "0.1.0", path = "../executor" }

# CLI-specific dependencies
sc-cli = { version = "0.9.0", optional = true, path = "../../substrate/client/cli" }
frame-benchmarking-cli = { version = "3.0.0", optional = true, path = "../../substrate/utils/frame/benchmarking-cli" }
node-inspect = { package = "nft360-inspect", version = "0.1.0", optional = true, path = "../inspect" }
try-runtime-cli = { version = "0.9.0", optional = true, path = "../../substrate/utils/frame/try-runtime/cli" }

# WASM-specific dependencies
wasm-bindgen = { version = "0.2.73", optional = true }
wasm-bindgen-futures = { version = "0.4.18", optional = true }
browser-utils = { package = "substrate-browser-utils", path = "../../substrate/utils/browser", optional = true, version = "0.9.0"}
libp2p-wasm-ext = { version = "0.28", features = ["websocket"], optional = true }

[target.'cfg(target_arch="x86_64")'.dependencies]
node-executor = { package="nft360-executor", version = "0.1.0", path = "../executor", features = [ "wasmtime" ] }
sc-cli = { version = "0.9.0", optional = true, path = "../../substrate/client/cli", features = [ "wasmtime" ] }
sc-service = { version = "0.9.0", default-features = false, path = "../../substrate/client/service", features = [ "wasmtime" ] }
sp-trie = { version = "3.0.0", default-features = false, path = "../../substrate/primitives/trie", features = ["memory-tracker"] }

[dev-dependencies]
sc-keystore = { version = "3.0.0", path = "../../substrate/client/keystore" }
sc-consensus = { version = "0.9.0", path = "../../substrate/client/consensus/common" }
sc-consensus-babe = { version = "0.9.0", path = "../../substrate/client/consensus/babe" }
sc-consensus-epochs = { version = "0.9.0", path = "../../substrate/client/consensus/epochs" }
sc-service-test = { version = "2.0.0", path = "../../substrate/client/service/test" }
futures = "0.3.9"
tempfile = "3.1.0"
assert_cmd = "1.0"
nix = "0.19"
serde_json = "1.0"
regex = "1"
platforms = "1.1"
async-std = { version = "1.6.5", features = ["attributes"] }
soketto = "0.4.2"

[build-dependencies]
structopt = { version = "0.3.8", optional = true }
node-inspect = { package = "nft360-inspect", version = "0.1.0", optional = true, path = "../inspect" }
frame-benchmarking-cli = { version = "3.0.0", optional = true, path = "../../substrate/utils/frame/benchmarking-cli" }
substrate-build-script-utils = { version = "3.0.0", optional = true, path = "../../substrate/utils/build-script-utils" }
substrate-frame-cli = { version = "3.0.0", optional = true, path = "../../substrate/utils/frame/frame-utilities-cli" }
try-runtime-cli = { version = "0.9.0", optional = true, path = "../../substrate/utils/frame/try-runtime/cli" }
sc-cli = { version = "0.9.0", optional = true, path = "../../substrate/client/cli"  }

[features]
default = [ "cli" ]
browser = [
	"browser-utils",
	"wasm-bindgen",
	"wasm-bindgen-futures",
	"libp2p-wasm-ext",
]
cli = [
	"node-executor/wasmi-errno",
	"node-inspect",
	"sc-cli",
	"frame-benchmarking-cli",
	"substrate-frame-cli",
	"sc-service/db",
	"sc-finality-grandpa-warp-sync",
	"structopt",
	"substrate-build-script-utils",
	"try-runtime-cli",
]
runtime-benchmarks = [
	"node-runtime/runtime-benchmarks",
	"frame-benchmarking-cli",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
# try-runtime = [
# 	"node-runtime/try-runtime",
# 	"try-runtime-cli",
# ]
