name: Build and Test

env:
  RUST_TOOLCHAIN: nightly-2021-07-03

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/cache@v2
        with:
          key: ${{ env.GITHUB_JOB }}-${{ env.RUST_TOOLCHAIN }}-${{ hashFiles('Cargo.lock', 'substrate/Cargo.lock') }}
          path: |
            ${{ env.HOME }}/.cargo
            ${{ github.workspace }}/target
            ${{ github.workspace }}/substrate/target
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          target: wasm32-unknown-unknown
      - name: Run tests
        run: cargo test --all

  formatting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          components: rustfmt
      - name: Ensure Standard Formatting
        run: cargo fmt -- --check